import type {Metadata} from "next";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v13-appRouter';
import {ThemeProvider} from '@mui/material/styles';
import {Inter} from "next/font/google";

import theme from "@/theme";
import {Container} from "@mui/material";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
            <html lang="en" style={{height: "100%"}}>
            <body className={inter.className} style={{height: "100%", padding: 0, margin: 0}}>
            <AppRouterCacheProvider>
                <ThemeProvider theme={theme}>
                    <Container maxWidth={'lg'} sx={{height: 1}}>
                        {children}
                    </Container>
                </ThemeProvider>
            </AppRouterCacheProvider>

            </body>
            </html>
    );
}
